name: selenium functional tests

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-test-selenium:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest]
                
    steps:
    - uses: actions/checkout@v3

    - name: tasklist1
      run: tasklist

    - name: start cmd /c pause
      shell: cmd
      run: start cmd /c pause

    - name: tasklist2
      run: tasklist

