name: selenium functional tests

on:
  pull_request:
    branches: [ master ]

jobs:
  build-and-run-app:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      
    - name: Install main solution dependencies
      run: dotnet restore
      working-directory: ./src
      
    - name: Build main solution
      run: dotnet build --configuration Release --no-restore
      working-directory: ./src
    
    - name: Run main solution
      run: |
        dotnet run --project SeleniumTests --launch-profile https --configuration Release --no-build --no-restore
      working-directory: ./src
      
  build-and-test-selenium:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      
    - name: Install test solution dependencies
      run: dotnet restore
      working-directory: ./tests/Functional
      
    - name: Build test solution
      run: dotnet build --configuration Release --no-restore
      working-directory: ./tests/Functional
      
    - name: Wait for asp.net
      run: sleep 60
      
    - name: Test
      run: dotnet test --configuration Release --no-build --no-restore
      working-directory: ./tests/Functional
