name: selenium functional tests

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-test-selenium:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest]
                
    steps:
    - uses: actions/checkout@v3

    - name: tasklist1
      shell: cmd
      run: set RUNNER_TRACKING_ID && tasklist

    - name: start cmd /c pause
      shell: cmd
      run: set RUNNER_TRACKING_ID && set RUNNER_TRACKING_ID="" && start cmd /c "set RUNNER_TRACKING_ID && ping 172.0.0.1 -n 2000"

    - name: tasklist2
      shell: cmd
      run: set RUNNER_TRACKING_ID && tasklist

